In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np

In [12]:
a = np.array([1,2,3]) #1d array
print(a)
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],
             [4,5,6]]) #2d array, note the double square brackets
print(b)
print(b.shape) #shape is a 2 rows, 3 colums array
print(b[0,0])

c = np.array([1.0, 2.1, 3.4]) #can be floats
print(c)

[1 2 3]
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1
[1.  2.1 3.4]


In [19]:
a = np.zeros((2,3)) #can make an array of all 0's. This will make a 2 row, 3 column array of zeros
print(a)

b = np.ones((2,3))
print(b)

c = np.full((2,3), 7) #will give a 2x3 array filled with 7s
print(c)

e = np.random.random((3,3)) #will give a random array 3x3
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.41808782 0.9879027  0.54640769]
 [0.80535465 0.42723199 0.12211005]
 [0.12946096 0.36561133 0.73292951]]


In [27]:
a = np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
print(a)

#slicing

b = a[:2, 1:3] #first two rows (0 and 1), and columns 1 and 2. 0 is first column. 3 is not included
print(b)

print(a[0,1])
b[0,0] = 75
print(a[0,1])
print(a) #basically, changing the sub array b, changes main array too

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
75
[[ 1 75  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
a = np.array([[1,2],
             [3,4],
             [5,6]])
print(a)

print(a > 2)

print( a[a>2]) # boolean array

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [45]:
#array math

x = np.array([[1,2],
             [3,4]])
y = np.array([[5,6],
             [7,8]])

print(x+y) #add array element wise
print(np.add(x,y)) #does same thing as above

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))


print(np.sum(x)) #add all elements of the array

print(np.sum(x, axis=0)) #sum of columns
print(np.sum(x, axis=1)) #sum of rows

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
10
[4 6]
[3 7]
